// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package camera_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 3;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {logic q;} camera_reg2hw_control_reg_t;

  typedef struct packed {logic q;} camera_reg2hw_status_reg_t;

  typedef struct packed {
    logic d;
    logic de;
  } camera_hw2reg_control_reg_t;

  typedef struct packed {
    logic d;
    logic de;
  } camera_hw2reg_status_reg_t;

  // Register -> HW type
  typedef struct packed {
    camera_reg2hw_control_reg_t control;  // [1:1]
    camera_reg2hw_status_reg_t  status;   // [0:0]
  } camera_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    camera_hw2reg_control_reg_t control;  // [3:2]
    camera_hw2reg_status_reg_t  status;   // [1:0]
  } camera_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] CAMERA_CONTROL_OFFSET = 3'h0;
  parameter logic [BlockAw-1:0] CAMERA_STATUS_OFFSET = 3'h4;

  // Register index
  typedef enum int {
    CAMERA_CONTROL,
    CAMERA_STATUS
  } camera_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] CAMERA_PERMIT[2] = '{
      4'b0001,  // index[0] CAMERA_CONTROL
      4'b0001  // index[1] CAMERA_STATUS
  };

endpackage

